#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-hoe-mercurial
Version  : 1.4.1
Release  : 8
URL      : https://rubygems.org/downloads/hoe-mercurial-1.4.1.gem
Source0  : https://rubygems.org/downloads/hoe-mercurial-1.4.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-hoe
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= (Another) Mercurial Plugin for hoe
* http://bitbucket.org/ged/hoe-mercurial
== Description

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n hoe-mercurial-1.4.1
gem spec %{SOURCE0} -l --ruby > rubygem-hoe-mercurial.gemspec

%build
gem build rubygem-hoe-mercurial.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
hoe-mercurial-1.4.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/hoe-mercurial-1.4.1
rake --trace test TESTOPTS="-v"
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/hoe-mercurial-1.4.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/hoe-mercurial-1.4.1/ChangeLog
/usr/lib64/ruby/gems/2.3.0/gems/hoe-mercurial-1.4.1/History.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-mercurial-1.4.1/Manifest.txt
/usr/lib64/ruby/gems/2.3.0/gems/hoe-mercurial-1.4.1/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/hoe-mercurial-1.4.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/hoe-mercurial-1.4.1/lib/hoe/mercurial.rb
/usr/lib64/ruby/gems/2.3.0/specifications/hoe-mercurial-1.4.1.gemspec
